language: python
sudo: false
python:
- '2.7'
install:
- pip install -U Sphinx
script:
- make allhtml
after_success:
- CURRENT_HASH=`git rev-parse HEAD`
- export RELEASE_VERSION=`git tag | tail -n 1`
- RELEASE_HASH=`git rev-list $RELEASE_VERSION -n 1`
- if [ "$CURRENT_HASH" = "$RELEASE_HASH"  ]; then export DEPLOY_DOCS=true; fi
- test -z "$DEPLOY_DOCS" || openssl aes-256-cbc -K $encrypted_15c7e38b27fc_key -iv $encrypted_15c7e38b27fc_iv
  -in stormpath_documentation_auto_doc_build.enc -out ~/.ssh/id_rsa -d
- test -z "$DEPLOY_DOCS" || chmod 600 ~/.ssh/id_rsa
- test -z "$DEPLOY_DOCS" || git config --global user.email "evangelists@stormpath.com"
- test -z "$DEPLOY_DOCS" || git config --global user.name "stormpath-documentation
  Auto Doc Build"
- test -z "$DEPLOY_DOCS" || git clone git@github.com:stormpath/stormpath.github.io.git
- test -z "$DEPLOY_DOCS" || cd stormpath.github.io
- test -z "$DEPLOY_DOCS" || git fetch origin source:source
- test -z "$DEPLOY_DOCS" || git checkout source
- test -z "$DEPLOY_DOCS" || rm -rf source/rest/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/rest/product-guide/latest && cp -r ../build/html/rest source/rest/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/php/product-guide/latest && cp -r ../build/html/php source/php/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/java/product-guide/latest && cp -r ../build/html/java source/java/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/csharp/product-guide/latest && cp -r ../build/html/csharp source/csharp/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/vbnet/product-guide/latest && cp -r ../build/html/vbnet source/vbnet/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/python/product-guide/latest && cp -r ../build/html/python source/python/product-guide/latest
- test -z "$DEPLOY_DOCS" || rm -rf source/nodejs/product-guide/latest && cp -r ../build/html/nodejs source/nodejs/product-guide/latest
- test -z "$DEPLOY_DOCS" || git add --all
- test -z "$DEPLOY_DOCS" || git commit -m "stormpath-documentation release $RELEASE_VERSION"
- test -z "$DEPLOY_DOCS" || git push origin source
- test -z "$DEPLOY_DOCS" || gem install bundler
- test -z "$DEPLOY_DOCS" || bundle install
- test -z "$DEPLOY_DOCS" || rake setup_github_pages[git@github.com:stormpath/stormpath.github.io.git]
- test -z "$DEPLOY_DOCS" || cd _deploy
- test -z "$DEPLOY_DOCS" || git pull --no-edit -s recursive -X theirs https://github.com/stormpath/stormpath.github.io.git
- test -z "$DEPLOY_DOCS" || cd ..
- test -z "$DEPLOY_DOCS" || rake generate
- test -z "$DEPLOY_DOCS" || cd _deploy
- test -z "$DEPLOY_DOCS" || git pull --no-edit -s recursive -X theirs https://github.com/stormpath/stormpath.github.io.git
- test -z "$DEPLOY_DOCS" || cd ..
- test -z "$DEPLOY_DOCS" || rake deploy
